# Generated by Django 5.2.5 on 2025-09-03 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='modelselection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sophia_agent', models.BooleanField(default=True)),
                ('weight_loss_agent', models.BooleanField(default=False)),
                ('cgm_agent', models.BooleanField(default=False)),
                ('dme_agent', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='weightlosspatient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('has_prescription', models.BooleanField(default=False)),
                ('delivery_method', models.CharField(blank=True, choices=[('pickup', 'Pickup'), ('delivery_standard', 'Delivery ($20)'), ('delivery_same_day', 'Same-day Delivery ($30)')], max_length=20, null=True)),
                ('callback_requested', models.BooleanField(default=False)),
                ('callback_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
