# Generated by Django 5.2.5 on 2025-09-03 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weightloss_agent', '0002_conversationhistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weightlosspatient',
            old_name='has_prescription',
            new_name='prescription_uploaded',
        ),
        migrations.CreateModel(
            name='WeightLossAgentPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_path', models.TextField(null=True)),
                ('patient_obj', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weightloss_patient_foreing_key', to='weightloss_agent.weightlosspatient')),
            ],
        ),
    ]
