# Generated by Django 5.2.5 on 2025-09-03 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weightloss_agent', '0003_rename_has_prescription_weightlosspatient_prescription_uploaded_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationhistory',
            name='session_id',
            field=models.IntegerField(null=True),
        ),
    ]
