# Generated by Django 5.2.5 on 2025-09-04 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weightloss_agent', '0004_conversationhistory_session_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='DMEModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('item_requested', models.TextField(null=True)),
                ('insurance_status', models.TextField(null=True)),
                ('prescription_status', models.TextField(null=True)),
                ('callback_requested', models.BooleanField(default=False)),
                ('callback_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
