# Generated by Django 5.2.5 on 2025-09-05 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weightloss_agent', '0005_dmemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='CGMLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('delivery_address', models.TextField(blank=True, null=True)),
                ('has_insurance', models.BooleanField(default=False)),
                ('insurance_name', models.CharField(blank=True, max_length=255, null=True)),
                ('bin_number', models.CharField(blank=True, max_length=50, null=True)),
                ('pcn_number', models.CharField(blank=True, max_length=50, null=True)),
                ('group_number', models.CharField(blank=True, max_length=50, null=True)),
                ('member_id', models.CharField(blank=True, max_length=100, null=True)),
                ('insurance_card_photo', models.URLField(blank=True, null=True)),
                ('diabetes_diagnosis', models.CharField(blank=True, choices=[('Type 1', 'Type 1'), ('Type 2', 'Type 2'), ('Other', 'Other')], max_length=50, null=True)),
                ('on_insulin', models.BooleanField(default=False)),
                ('blood_sugar_testing_frequency', models.CharField(blank=True, max_length=100, null=True)),
                ('hypoglycemia_history', models.BooleanField(default=False)),
                ('recent_a1c', models.CharField(blank=True, max_length=20, null=True)),
                ('has_doctor', models.BooleanField(default=False)),
                ('doctor_name', models.CharField(blank=True, max_length=255, null=True)),
                ('doctor_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('has_prescription', models.BooleanField(default=False)),
                ('has_medical_necessity', models.BooleanField(default=False)),
                ('telehealth_requested', models.BooleanField(default=False)),
                ('docs_received', models.BooleanField(default=False)),
                ('needs_callback', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='dmemodel',
            name='BIN',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='dmemodel',
            name='Group',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='dmemodel',
            name='Member_ID',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='dmemodel',
            name='PCN',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='dmemodel',
            name='photo_url',
            field=models.TextField(null=True),
        ),
    ]
