# Generated by Django 5.2.5 on 2025-09-05 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weightloss_agent', '0006_cgmlead_dmemodel_bin_dmemodel_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cgmlead',
            name='session_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='cgmlead',
            name='date_of_birth',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='cgmlead',
            name='full_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
