# Generated by Django 5.2.5 on 2025-09-05 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weightloss_agent', '0007_cgmlead_session_id_alter_cgmlead_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dmemodel',
            name='session_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='modelselection',
            name='session_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='weightlosspatient',
            name='session_id',
            field=models.IntegerField(null=True),
        ),
    ]
