# Generated by Django 5.2.5 on 2025-09-05 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weightloss_agent', '0008_dmemodel_session_id_modelselection_session_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cgmlead',
            name='session_id',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='conversationhistory',
            name='session_id',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='dmemodel',
            name='session_id',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='modelselection',
            name='session_id',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='weightlosspatient',
            name='session_id',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
    ]
