# Generated by Django 5.2.5 on 2025-09-05 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weightloss_agent', '0009_alter_cgmlead_session_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cgmlead',
            name='docs_received',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='cgmlead',
            name='has_doctor',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='cgmlead',
            name='has_insurance',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='cgmlead',
            name='has_medical_necessity',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='cgmlead',
            name='has_prescription',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='cgmlead',
            name='hypoglycemia_history',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='cgmlead',
            name='needs_callback',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='cgmlead',
            name='on_insulin',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='cgmlead',
            name='telehealth_requested',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='dmemodel',
            name='callback_requested',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='modelselection',
            name='cgm_agent',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='modelselection',
            name='dme_agent',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='modelselection',
            name='sophia_agent',
            field=models.TextField(default=True),
        ),
        migrations.AlterField(
            model_name='modelselection',
            name='weight_loss_agent',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='weightlosspatient',
            name='callback_requested',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='weightlosspatient',
            name='prescription_uploaded',
            field=models.TextField(null=True),
        ),
    ]
