# Generated by Django 5.2.5 on 2025-09-05 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weightloss_agent', '0010_alter_cgmlead_docs_received_alter_cgmlead_has_doctor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelselection',
            name='sophia_agent',
            field=models.TextField(null=True),
        ),
    ]
