# Generated by Django 5.2.5 on 2025-09-06 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weightloss_agent', '0011_alter_modelselection_sophia_agent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cgmlead',
            old_name='insurance_card_photo',
            new_name='photo_1',
        ),
        migrations.RemoveField(
            model_name='dmemodel',
            name='photo_url',
        ),
        migrations.AddField(
            model_name='cgmlead',
            name='photo_2',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cgmlead',
            name='photo_3',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dmemodel',
            name='photo_1',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dmemodel',
            name='photo_2',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weightlosspatient',
            name='photo_1',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cgmlead',
            name='docs_received',
            field=models.TextField(default='False'),
        ),
        migrations.AlterField(
            model_name='cgmlead',
            name='has_doctor',
            field=models.TextField(default='False'),
        ),
        migrations.AlterField(
            model_name='cgmlead',
            name='has_insurance',
            field=models.TextField(default='False'),
        ),
        migrations.AlterField(
            model_name='cgmlead',
            name='has_medical_necessity',
            field=models.TextField(default='False'),
        ),
        migrations.AlterField(
            model_name='cgmlead',
            name='has_prescription',
            field=models.TextField(default='False'),
        ),
        migrations.AlterField(
            model_name='cgmlead',
            name='needs_callback',
            field=models.TextField(default='False'),
        ),
        migrations.AlterField(
            model_name='cgmlead',
            name='on_insulin',
            field=models.TextField(default='False'),
        ),
        migrations.AlterField(
            model_name='cgmlead',
            name='telehealth_requested',
            field=models.TextField(default='False'),
        ),
        migrations.AlterField(
            model_name='dmemodel',
            name='callback_requested',
            field=models.TextField(default='False'),
        ),
        migrations.AlterField(
            model_name='dmemodel',
            name='insurance_status',
            field=models.TextField(default='False'),
        ),
        migrations.AlterField(
            model_name='dmemodel',
            name='prescription_status',
            field=models.TextField(default='False'),
        ),
        migrations.AlterField(
            model_name='modelselection',
            name='cgm_agent',
            field=models.TextField(default='False', null=True),
        ),
        migrations.AlterField(
            model_name='modelselection',
            name='dme_agent',
            field=models.TextField(default='False', null=True),
        ),
        migrations.AlterField(
            model_name='modelselection',
            name='sophia_agent',
            field=models.TextField(default='True', null=True),
        ),
        migrations.AlterField(
            model_name='modelselection',
            name='weight_loss_agent',
            field=models.TextField(default='False', null=True),
        ),
        migrations.AlterField(
            model_name='weightlosspatient',
            name='callback_requested',
            field=models.TextField(default='False'),
        ),
        migrations.DeleteModel(
            name='WeightLossAgentPhoto',
        ),
    ]
