# Generated by Django 5.2.5 on 2025-09-06 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weightloss_agent', '0012_rename_insurance_card_photo_cgmlead_photo_1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SophiaLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('medication_name', models.CharField(blank=True, max_length=255, null=True)),
                ('inquiry_type', models.CharField(choices=[('availability', 'Medication/Stock Availability'), ('refill', 'Refill'), ('transfer', 'Transfer'), ('insurance', 'Insurance Inquiry'), ('provider', 'Provider Inquiry'), ('other', 'Other')], default='other', max_length=50)),
                ('callback_requested', models.BooleanField(default=False)),
                ('urgent', models.BooleanField(default=False)),
                ('controlled_medication', models.BooleanField(default=False)),
                ('session_id', models.CharField(db_index=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
