# Generated by Django 5.2.5 on 2025-09-07 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weightloss_agent', '0013_sophialead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dmemodel',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dmemodel',
            name='phone',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sophialead',
            name='date_of_birth',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='weightlosspatient',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='weightlosspatient',
            name='phone',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
